<!ENTITY % susemanager-entities SYSTEM "susemanager-decl.ent">
<!ENTITY % sgml.features "IGNORE">
<!ENTITY % xml.features "INCLUDE">
<!ENTITY % dbcent PUBLIC "-//OASIS//ENTITIES DocBook Character
"&exampleuser;" => "{tux}",
"&exampleuserII;" => "{wilber}",
"&examplegroup;" => "{users}",
"&rootuser;" => "{<systemitem xmlns='http://docbook.org/ns/docbook' class='username'>root</systemitem>}",
"&grub;" => "{GRUB}",
"&suse;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>SUSE</phrase>}",
"&novell;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>Novell</phrase>}",
"&x86;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>x86</phrase>}",
"&amd64;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>AMD64</phrase>}",
"&s390;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>S/390</phrase>}",
"&zsystems;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>z Systems</phrase>}",
"&zseries;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>z Systems</phrase>}",
"&ipf;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>Itanium</phrase>}",
"&ipseries;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>POWER</phrase>}",
"&ppc;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>POWER</phrase>}",
"&em64t;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>Intel EM64T</phrase>}",
"&intel64;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>Intel 64</phrase>}",
"&power;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>POWER</phrase>}",
"&ppc64le;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>ppc64le</phrase>}",
"&suselinux;" => "{&suse; Linux}",
"&yast;" => "{YaST}",
"&yastcc;" => "{&yast; Control Center}",
"&ay;" => "{AutoYaST}",
"&openscap;" => "{OpenSCAP}",
"&deploy;" => "{Deployment Guide}",
"&slea;" => "{SLE}",
"&slsa;" => "{SLES}",
"&sls;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>SUSE Linux Enterprise Server</phrase>}",
"&sle;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>SUSE Linux Enterprise</phrase>}",
"&sled;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>SUSE Linux Enterprise Desktop</phrase>}",
"&productname;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>SUSE Manager</phrase>}",
"&productnumber;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>3.1</phrase>}",
"&productnumber3;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>3</phrase>}",
"&sdk;" => "{SUSE Software Development Kit}",
"&ncc;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>Novell Customer Center</phrase>}",
"&scc;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>SUSE Customer Center</phrase>}",
"&susemgr;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>&suse; Manager</phrase>}",
"&susemgrdb;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>&suse; Manager with Database</phrase>}",
"&susemgrproxy;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>&susemgr; Proxy</phrase>}",
"&mgrquick;" => "{Quick Start}",
"&mgrproxyquick;" => "{Proxy Quick Start}",
"&slereg;" => "{SUSE&reg; Linux Enterprise}",
"&susemgrreg;" => "{&suse;&reg; Manager}",
"&thrdmrk;" => "{*}",
"&kiwi;" => "{KIWI}",
"&kickstart;" => "{Kickstart}",
"&smtool;" => "{Subscription Management Tool}",
"&smt;" => "{SMT}",
"&xen;" => "{Xen}",
"&xenreg;" => "{Xen&reg;}",
"&kvm;" => "{KVM}",
"&vmhost;" => "{VM Host Server}",
"&vmguest;" => "{VM Guest}",
"&susestudio;" => "{&suse; Studio}",
"&prompt.root;" => "{<prompt xmlns='http://docbook.org/ns/docbook'>root # </prompt>}",
"&prompt.user;" => "{<prompt xmlns='http://docbook.org/ns/docbook'>&exampleuser; &gt; </prompt>}",
"&prompt.user2;" => "{<prompt xmlns='http://docbook.org/ns/docbook'>&exampleuserII; &gt; </prompt>}",
"&euro;" => "{&#x20AC;}",
<!ENTITY % network-entities SYSTEM "network-decl.ent">
<!ENTITY % susemgr-entities SYSTEM "susemanager-decl.ent">
