<!ENTITY % susemanager-entities SYSTEM "susemanager-decl.ent">
<!ENTITY % sgml.features "IGNORE">
<!ENTITY % xml.features "INCLUDE">
<!ENTITY % dbcent PUBLIC "-//OASIS//ENTITIES DocBook Character
"<!ENTITY exampleuser    "tux">exampleuser;" => "{tux}",
"<!ENTITY exampleuserII  "wilber">exampleuserII;" => "{wilber}",
"<!ENTITY examplegroup   "users">examplegroup;" => "{users}",
"<!ENTITY rootuser       "<systemitem xmlns='http://docbook.org/ns/docbook' class='username'>root</systemitem>">rootuser;" => "{<systemitem xmlns='http://docbook.org/ns/docbook' class='username'>root</systemitem>}",
"<!ENTITY grub           "GRUB">grub;" => "{GRUB}",
"<!ENTITY suse           "<phrase xmlns='http://docbook.org/ns/docbook'>SUSE</phrase>">suse;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>SUSE</phrase>}",
"<!ENTITY novell         "<phrase xmlns='http://docbook.org/ns/docbook'>Novell</phrase>">novell;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>Novell</phrase>}",
"<!ENTITY x86           "<phrase xmlns='http://docbook.org/ns/docbook'>x86</phrase>">x86;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>x86</phrase>}",
"<!ENTITY amd64         "<phrase xmlns='http://docbook.org/ns/docbook'>AMD64</phrase>">amd64;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>AMD64</phrase>}",
"<!ENTITY s390          "<phrase xmlns='http://docbook.org/ns/docbook'>S/390</phrase>">s390;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>S/390</phrase>}",
"<!ENTITY zsystems      "<phrase xmlns='http://docbook.org/ns/docbook'>z Systems</phrase>">zsystems;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>z Systems</phrase>}",
"<!ENTITY zseries       "<phrase xmlns='http://docbook.org/ns/docbook'>z Systems</phrase>">zseries;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>z Systems</phrase>}",
"<!ENTITY ipf           "<phrase xmlns='http://docbook.org/ns/docbook'>Itanium</phrase>">ipf;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>Itanium</phrase>}",
"<!ENTITY ipseries      "<phrase xmlns='http://docbook.org/ns/docbook'>POWER</phrase>">ipseries;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>POWER</phrase>}",
"<!ENTITY ppc           "<phrase xmlns='http://docbook.org/ns/docbook'>POWER</phrase>">ppc;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>POWER</phrase>}",
"<!ENTITY em64t         "<phrase xmlns='http://docbook.org/ns/docbook'>Intel EM64T</phrase>">em64t;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>Intel EM64T</phrase>}",
"<!ENTITY intel64       "<phrase xmlns='http://docbook.org/ns/docbook'>Intel 64</phrase>">intel64;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>Intel 64</phrase>}",
"<!ENTITY power         "<phrase xmlns='http://docbook.org/ns/docbook'>POWER</phrase>">power;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>POWER</phrase>}",
"<!ENTITY ppc64le       "<phrase xmlns='http://docbook.org/ns/docbook'>ppc64le</phrase>">ppc64le;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>ppc64le</phrase>}",
"<!ENTITY suselinux      "&suse; Linux">suselinux;" => "{&suse; Linux}",
"<!ENTITY yast           "YaST">yast;" => "{YaST}",
"<!ENTITY yastcc         "&yast; Control Center">yastcc;" => "{&yast; Control Center}",
"<!ENTITY ay             "AutoYaST">ay;" => "{AutoYaST}",
"<!ENTITY openscap        "OpenSCAP">openscap;" => "{OpenSCAP}",
"<!ENTITY deploy         "Deployment Guide"> deploy;" => "{Deployment Guide}",
"<!ENTITY slea          "SLE">slea;" => "{SLE}",
"<!ENTITY slsa          "SLES">slsa;" => "{SLES}",
"<!ENTITY sls           "<phrase xmlns='http://docbook.org/ns/docbook'>SUSE Linux Enterprise Server</phrase>">sls;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>SUSE Linux Enterprise Server</phrase>}",
"<!ENTITY sle            "<phrase xmlns='http://docbook.org/ns/docbook'>SUSE Linux Enterprise</phrase>">sle;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>SUSE Linux Enterprise</phrase>}",
"<!ENTITY sled           "<phrase xmlns='http://docbook.org/ns/docbook'>SUSE Linux Enterprise Desktop</phrase>">sled;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>SUSE Linux Enterprise Desktop</phrase>}",
"<!ENTITY productname    "<phrase xmlns='http://docbook.org/ns/docbook'>SUSE Manager</phrase>">productname;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>SUSE Manager</phrase>}",
"<!ENTITY productnumber  "<phrase xmlns='http://docbook.org/ns/docbook'>3.1</phrase>">productnumber;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>3.1</phrase>}",
"<!ENTITY productnumber3 "<phrase xmlns='http://docbook.org/ns/docbook'>3</phrase>">productnumber3;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>3</phrase>}",
"<!ENTITY sdk            "SUSE Software Development Kit">sdk;" => "{SUSE Software Development Kit}",
"<!ENTITY ncc            "<phrase xmlns='http://docbook.org/ns/docbook'>Novell Customer Center</phrase>">ncc;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>Novell Customer Center</phrase>}",
"<!ENTITY scc            "<phrase xmlns='http://docbook.org/ns/docbook'>SUSE Customer Center</phrase>">scc;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>SUSE Customer Center</phrase>}",
"<!ENTITY susemgr        "<phrase xmlns='http://docbook.org/ns/docbook'>&suse; Manager</phrase>">susemgr;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>&suse; Manager</phrase>}",
"<!ENTITY susemgrdb      "<phrase xmlns='http://docbook.org/ns/docbook'>&suse; Manager with Database</phrase>">susemgrdb;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>&suse; Manager with Database</phrase>}",
"<!ENTITY susemgrproxy   "<phrase xmlns='http://docbook.org/ns/docbook'>&susemgr; Proxy</phrase>">susemgrproxy;" => "{<phrase xmlns='http://docbook.org/ns/docbook'>&susemgr; Proxy</phrase>}",
"<!ENTITY mgrquick       "Quick Start">mgrquick;" => "{Quick Start}",
"<!ENTITY mgrproxyquick  "Proxy Quick Start">mgrproxyquick;" => "{Proxy Quick Start}",
"<!ENTITY slereg        "SUSE&reg; Linux Enterprise">slereg;" => "{SUSE&reg; Linux Enterprise}",
"<!ENTITY susemgrreg    "&suse;&reg; Manager">susemgrreg;" => "{&suse;&reg; Manager}",
"<!ENTITY thrdmrk       "*">thrdmrk;" => "{*}",
"<!ENTITY kiwi            "KIWI">kiwi;" => "{KIWI}",
"<!ENTITY kickstart       "Kickstart">kickstart;" => "{Kickstart}",
"<!ENTITY smtool        "Subscription Management Tool">smtool;" => "{Subscription Management Tool}",
"<!ENTITY smt           "SMT">smt;" => "{SMT}",
"<!ENTITY xen           "Xen">xen;" => "{Xen}",
"<!ENTITY xenreg        "Xen&reg;">xenreg;" => "{Xen&reg;}",
"<!ENTITY kvm           "KVM">kvm;" => "{KVM}",
"<!ENTITY vmhost        "VM Host Server">vmhost;" => "{VM Host Server}",
"<!ENTITY vmguest       "VM Guest">vmguest;" => "{VM Guest}",
"<!ENTITY susestudio     "&suse; Studio">susestudio;" => "{&suse; Studio}",
"<!ENTITY prompt.root     "<prompt xmlns='http://docbook.org/ns/docbook'>root # </prompt>">prompt.root;" => "{<prompt xmlns='http://docbook.org/ns/docbook'>root # </prompt>}",
"<!ENTITY prompt.user     "<prompt xmlns='http://docbook.org/ns/docbook'>&exampleuser; &gt; </prompt>">prompt.user;" => "{<prompt xmlns='http://docbook.org/ns/docbook'>&exampleuser; &gt; </prompt>}",
"<!ENTITY prompt.user2    "<prompt xmlns='http://docbook.org/ns/docbook'>&exampleuserII; &gt; </prompt>">prompt.user2;" => "{<prompt xmlns='http://docbook.org/ns/docbook'>&exampleuserII; &gt; </prompt>}",
"<!ENTITY euro            "&#x20AC;">euro;" => "{&#x20AC;}",
<!ENTITY % network-entities SYSTEM "network-decl.ent">
<!ENTITY % susemgr-entities SYSTEM "susemanager-decl.ent">
